<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
	<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
	<PublishTrimmed>false</PublishTrimmed>
	 <TrimMode>none</TrimMode>
	 <!-- Esto evita optimizaciones de tipos genéricos que rompen LINQ -->
	 <IlcGenerateCompleteTypeMetadata>true</IlcGenerateCompleteTypeMetadata>
	 <IlcGenerateStackTraceData>true</IlcGenerateStackTraceData>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Gotho.BlazorPdf.MudBlazor" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.2" />
	<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.2" />  
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.2" />
    <PackageReference Include="MudBlazor" Version="8.15.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />	
  </ItemGroup>

  <ItemGroup>
		<TrimmerRootAssembly Include="System.Linq" />
		<TrimmerRootAssembly Include="System.Linq.Expressions" />
	    <TrimmerRootDescriptor Include="TrimmerConfig.xml" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties wwwroot_4appsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>
	
</Project>
